
qlib_init:
  provider_uri: "/Users/dabai/liepin/study/llm/Financial_QA/data/qlib_data/cn_data_etf"
  region: cn
  exp_manager:
    class: "MLflowExpManager"
    module_path: "qlib.workflow.expm"
    kwargs:
      uri: "file:/Users/dabai/liepin/study/llm/Financial_QA/data/qlib_exp/mlruns"
      default_exp_name: "lgb_exp_tree_import"

market: &market zxzz399101
benchmark: &benchmark SZ510210

data_handler_config: &data_handler_config
  start_time: 2015-01-01
  end_time: 2025-12-30
  fit_start_time: 2015-01-01 # 特征处理器（Processor）的拟合区间 主要用于：RobustZScoreNorm ZScoreNorm CSRankNorm Fillna
  fit_end_time: 2016-12-31
  instruments: *market
  infer_processors:
    - class: FilterCol
      kwargs:
        fields_group: feature
        col_list: [ "RESI5", "WVMA5", "RSQR5", "KLEN", "RSQR10", "CORR5", "CORD5", "CORR10", "ROC60", "RESI10", "VSTD5", "RSQR60", "CORR60", "WVMA60", "STD5", "RSQR20", "CORD60", "CORD10", "CORR20", "KLOW", "ROC20", "QTLD60", "QTLD30", "MIN10", "MIN30", "VMA60", "QTLD20", "MIN20", "MIN5", "MIN60", "MA30", "VSUMN60", "MA60", "QTLD10", "LOW0", "VSUMN30", "MA20", "ROC10", "VSUMN20", "VMA30", "MA10", "QTLU30", "QTLU60", "QTLD5", "SUMN30", "SUMN20", "VMA20", "VSTD60", "QTLU20", "ROC5", "VSUMN10", "SUMN60", "SUMN10", "MA5", "SUMN5", "VMA10", "VSUMN5", "QTLU10", "IMIN5", "VSTD30", "IMIN20", "IMIN30", "OPEN0", "VMA5", "IMIN10", "CNTN5", "QTLU5", "IMIN60", "CNTN10", "CNTN20", "VSTD20", "CNTN30", "MAX60", "CNTN60", "MAX30", "KLOW2", ]
  label: ["If(Ref($close, -18) / Ref($close, -1) - 1 > 0.001, 1, 0)"]


port_analysis_config: &port_analysis_config
  strategy:
    class: TopkDropoutStrategy
    module_path: qlib.contrib.strategy
    kwargs:
      signal: <PRED>
      topk: 5
      n_drop: 5
      hold_thresh: 5  # 周频 label 对齐
  backtest:
    start_time: 2017-03-02
    end_time: 2025-12-30
    account: 1000000
    benchmark: *benchmark
    exchange_kwargs:
      limit_threshold: 0.095
      deal_price: close
      open_cost: 0.0005
      close_cost: 0.0015
      min_cost: 5

task:
  model:
    class: LGBModel
    module_path: qlib.contrib.model.gbdt
    kwargs:
      loss: binary
      metric: ['binary_logloss','auc']
      colsample_bytree: 0.8879
      learning_rate: 0.03
      subsample: 0.8789
      lambda_l1: 5
      lambda_l2: 18
      max_depth: 4
      num_leaves: 31
      min_data_in_leaf: 100
      num_threads: 20
      feature_fraction_seed: 42
      bagging_seed: 42
  dataset:
    class: CustomDatasetH
    module_path: qlib_.train_test.rolling_train_class.custom_datasets
    kwargs:
      handler:
        class: Alpha158
        module_path: qlib.contrib.data.handler
        kwargs: *data_handler_config
      segments:
        train: [ 2015-01-01, 2016-12-31 ]
        valid: [ 2017-01-01, 2017-03-01 ]   # ratio 模式下无效
        test: [ 2017-03-02, 2025-12-30 ]
      dataset_type: ratio
      train_ratio: 0.8
  record:
    - class: SignalRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        model: <MODEL>
        dataset: <DATASET>
    - class: SigAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        ana_long_short: False
        ann_scaler: 252
    - class: PortAnaRecord
      module_path: qlib.workflow.record_temp
      kwargs:
        config: *port_analysis_config